`id`,
    `productname`,
    `idea_type`,
    `idea_abstract`,
    `idea_descr`,
    `author`,
    `idea_expiry`,
    `idea_risk`,
    `idea_instruments`,
    `idea_currency`,
    `idea_major`,
    `idea_minor`,
    `idea_region`,
    `idea_country`


    `id`,
    `fullName`,
    `username`,
    `userpassword`,
    `userphone`,
    `useremail`,
    `gender`,
    `address`,
    `role`